// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function ExecCommand(arg1) {
  return window['go']['main']['App']['ExecCommand'](arg1);
}

export function GetAvailabeFiles() {
  return window['go']['main']['App']['GetAvailabeFiles']();
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetDataXmlFiles() {
  return window['go']['main']['App']['GetDataXmlFiles']();
}

export function GetImage(arg1) {
  return window['go']['main']['App']['GetImage'](arg1);
}

export function GetImages() {
  return window['go']['main']['App']['GetImages']();
}

export function GetNoitaData(arg1) {
  return window['go']['main']['App']['GetNoitaData'](arg1);
}

export function GetNoitaDataFile(arg1) {
  return window['go']['main']['App']['GetNoitaDataFile'](arg1);
}

export function SaveComment(arg1, arg2) {
  return window['go']['main']['App']['SaveComment'](arg1, arg2);
}

export function SaveJson(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveJson'](arg1, arg2, arg3);
}

export function SaveTemplate(arg1, arg2) {
  return window['go']['main']['App']['SaveTemplate'](arg1, arg2);
}

export function StartExplorer(arg1) {
  return window['go']['main']['App']['StartExplorer'](arg1);
}

export function UnpackAssets() {
  return window['go']['main']['App']['UnpackAssets']();
}

export function UpdateSessionJson(arg1, arg2) {
  return window['go']['main']['App']['UpdateSessionJson'](arg1, arg2);
}

export function WindowAction(arg1) {
  return window['go']['main']['App']['WindowAction'](arg1);
}
