// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteTemplate(arg1:string):Promise<void>;

export function ExecCommand(arg1:{[key: string]: string}):Promise<void>;

export function GetAvailabeFiles():Promise<{[key: string]: main.FileStruct}>;

export function GetConfig(arg1:string):Promise<string>;

export function GetDataXmlFiles():Promise<{[key: string]: main.Entity_Struct}>;

export function GetImage(arg1:string):Promise<string>;

export function GetImages():Promise<{[key: string]: string}>;

export function GetNoitaData(arg1:string):Promise<{[key: string]: any}>;

export function GetNoitaDataFile(arg1:string):Promise<string>;

export function SaveComment(arg1:string,arg2:string):Promise<void>;

export function SaveJson(arg1:string,arg2:string,arg3:any):Promise<void>;

export function SaveTemplate(arg1:string,arg2:string):Promise<void>;

export function StartExplorer(arg1:{[key: string]: string}):Promise<void>;

export function UnpackAssets():Promise<void>;

export function UpdateSessionJson(arg1:string,arg2:main.SessionJsonStruct):Promise<void>;

export function WindowAction(arg1:{[key: string]: any}):Promise<void>;
